//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountForgetModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountForgetModel()
        {
            this.IsUsed = false;
    		OnInit();
        }
    
        public int AccountForgetID { get; set; }
        public int AccountID { get; set; }
        public string Token { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public bool IsUsed { get; set; }
    	
    	partial void OnInit();
    
        public virtual AccountModel AccountModel { get; set; }
    }
}
