//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSocialModel
    {
        public int AccountSocialID { get; set; }
        public int AccountID { get; set; }
        public string SocialID { get; set; }
        public int ProviderID { get; set; }
        public int Email { get; set; }
    
        public virtual AccountModel Account { get; set; }
    }
}
