//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class brackets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brackets()
        {
            this.matches = new HashSet<matches>();
            this.tournamentteambrackets = new HashSet<tournamentteambrackets>();
            this.tournamentusersbrackets = new HashSet<tournamentusersbrackets>();
        }
    
        public int BracketID { get; set; }
        public int BracketTypeID { get; set; }
        public bool Finalized { get; set; }
        public int NumberOfGroups { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public int MaxRounds { get; set; }
        public int NumberPlayersAdvance { get; set; }
        public bool IsLocked { get; set; }
    
        public virtual brackettypes brackettypes { get; set; }
        public virtual tournaments tournaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matches> matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentteambrackets> tournamentteambrackets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentusersbrackets> tournamentusersbrackets { get; set; }
    }
}
