//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatchModel()
        {
            this.Games = new HashSet<GameModel>();
    		OnInit();
        }
    
    	partial void OnInit();
    
        public int MatchID { get; set; }
        public int ChallengerID { get; set; }
        public int DefenderID { get; set; }
        public Nullable<int> WinnerID { get; set; }
        public Nullable<int> ChallengerScore { get; set; }
        public Nullable<int> DefenderScore { get; set; }
        public Nullable<int> RoundIndex { get; set; }
        public int MatchNumber { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.TimeSpan> MatchDuration { get; set; }
        public Nullable<int> MatchIndex { get; set; }
        public Nullable<int> NextMatchNumber { get; set; }
        public Nullable<int> PrevMatchIndex { get; set; }
        public Nullable<int> NextLoserMatchNumber { get; set; }
        public Nullable<int> PrevDefenderMatchNumber { get; set; }
        public Nullable<int> PrevChallengerMatchNumber { get; set; }
        public Nullable<int> MaxGames { get; set; }
        public Nullable<int> BracketID { get; set; }
        public bool IsManualWin { get; set; }
        public Nullable<int> GroupNumber { get; set; }
    
        public virtual BracketModel Bracket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameModel> Games { get; set; }
    }
}
