//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VictoriousEntities : DbContext
    {
        public VictoriousEntities()
            : base("name=VictoriousEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bracket> Brackets { get; set; }
        public virtual DbSet<BracketType> BracketTypes { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<TournamentRule> TournamentRules { get; set; }
        public virtual DbSet<Tournament> Tournaments { get; set; }
        public virtual DbSet<GameType> GameTypes { get; set; }
        public virtual DbSet<Challenger> Challengers { get; set; }
        public virtual DbSet<Defender> Defenders { get; set; }
        public virtual DbSet<TournamentUser> TournamentUsers { get; set; }
        public virtual DbSet<TournamentUsersBracket> TournamentUsersBrackets { get; set; }
    }
}
