//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class victoriousdatabaseEntities : DbContext
    {
        public victoriousdatabaseEntities()
            : base("name=victoriousdatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountforget> accountforget { get; set; }
        public virtual DbSet<accountinvites> accountinvites { get; set; }
        public virtual DbSet<accounts> accounts { get; set; }
        public virtual DbSet<brackets> brackets { get; set; }
        public virtual DbSet<brackettypes> brackettypes { get; set; }
        public virtual DbSet<games> games { get; set; }
        public virtual DbSet<gametypes> gametypes { get; set; }
        public virtual DbSet<mailinglist> mailinglist { get; set; }
        public virtual DbSet<matches> matches { get; set; }
        public virtual DbSet<platforms> platforms { get; set; }
        public virtual DbSet<siteteammembers> siteteammembers { get; set; }
        public virtual DbSet<siteteams> siteteams { get; set; }
        public virtual DbSet<tournamentinvites> tournamentinvites { get; set; }
        public virtual DbSet<tournaments> tournaments { get; set; }
        public virtual DbSet<tournamentteambrackets> tournamentteambrackets { get; set; }
        public virtual DbSet<tournamentteammembers> tournamentteammembers { get; set; }
        public virtual DbSet<tournamentteams> tournamentteams { get; set; }
        public virtual DbSet<tournamentusers> tournamentusers { get; set; }
        public virtual DbSet<tournamentusersbrackets> tournamentusersbrackets { get; set; }
    }
}
