//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteteammembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siteteammembers()
        {
            this.tournamentteammembers = new HashSet<tournamentteammembers>();
        }
    
        public int SiteTeamMemberID { get; set; }
        public int AccountID { get; set; }
        public int SiteTeamID { get; set; }
        public int Role { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual siteteams siteteams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentteammembers> tournamentteammembers { get; set; }
    }
}
