//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteTeamModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteTeamModel()
        {
            this.SiteTeamMembers = new HashSet<SiteTeamMemberModel>();
            this.TournamentTeamMembers = new HashSet<TournamentTeamModel>();
    		OnInit();
        }
    
    	partial void OnInit();
    
        public int SiteTeamID { get; set; }
        public string TeamName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteTeamMemberModel> SiteTeamMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentTeamModel> TournamentTeamMembers { get; set; }
    }
}
