//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentUserModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentUserModel()
        {
            this.IsCheckedIn = false;
            this.TournamentUsersBrackets = new HashSet<TournamentUsersBracketModel>();
    		OnInit();
        }
    
        public int TournamentUserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> UniformNumber { get; set; }
        public int TournamentID { get; set; }
        public Nullable<int> PermissionLevel { get; set; }
        public string Name { get; set; }
        public string InviteCode { get; set; }
        public bool IsCheckedIn { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
    	
    	partial void OnInit();
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentUsersBracketModel> TournamentUsersBrackets { get; set; }
        public virtual TournamentModel Tournament { get; set; }
    }
}
