//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentTeamMemberModel
    {
        public int TournamentTeamMemberID { get; set; }
        public int TournamentTeamID { get; set; }
        public int SiteTeamMemberID { get; set; }
    	
    	partial void OnInit();
    
        public virtual SiteTeamMemberModel SiteTeamMember { get; set; }
        public virtual TournamentTeamModel TournamentTeam { get; set; }
    }
}
