//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournamentusers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tournamentusers()
        {
            this.tournamentusersbrackets = new HashSet<tournamentusersbrackets>();
        }
    
        public int TournamentUserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> UniformNumber { get; set; }
        public int TournamentID { get; set; }
        public Nullable<int> PermissionLevel { get; set; }
        public string Name { get; set; }
        public string InviteCode { get; set; }
        public bool IsCheckedIn { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
    
        public virtual tournaments tournaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentusersbrackets> tournamentusersbrackets { get; set; }
    }
}
