//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournamentteams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tournamentteams()
        {
            this.tournamentteambrackets = new HashSet<tournamentteambrackets>();
            this.tournamentteammembers = new HashSet<tournamentteammembers>();
        }
    
        public int TournamentTeamID { get; set; }
        public int TournamentID { get; set; }
        public int SiteTeamID { get; set; }
        public int CreatedByID { get; set; }
        public string TeamName { get; set; }
    
        public virtual siteteams siteteams { get; set; }
        public virtual tournaments tournaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentteambrackets> tournamentteambrackets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentteammembers> tournamentteammembers { get; set; }
    }
}
