//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentRulesModel
    {
        public int TournamentRulesID { get; set; }
        public int NumberOfRounds { get; set; }
        public bool HasEntryFee { get; set; }
        public Nullable<decimal> EntryFee { get; set; }
        public decimal PrizePurse { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<System.DateTime> RegistrationStartDate { get; set; }
        public Nullable<System.DateTime> RegistrationEndDate { get; set; }
        public Nullable<System.DateTime> TournamentStartDate { get; set; }
        public Nullable<System.DateTime> TournamentEndDate { get; set; }
        public Nullable<System.DateTime> CheckInBegins { get; set; }
        public Nullable<System.DateTime> CheckInEnds { get; set; }
        public int Platform { get; set; }
    
        public virtual TournamentModel Tournament { get; set; }
    }
}
