//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournaments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tournaments()
        {
            this.brackets = new HashSet<brackets>();
            this.tournamentinvites = new HashSet<tournamentinvites>();
            this.tournamentteams = new HashSet<tournamentteams>();
            this.tournamentusers = new HashSet<tournamentusers>();
        }
    
        public int TournamentID { get; set; }
        public Nullable<int> GameTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByID { get; set; }
        public int WinnerID { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public int LastEditedByID { get; set; }
        public Nullable<decimal> EntryFee { get; set; }
        public decimal PrizePurse { get; set; }
        public System.DateTime RegistrationStartDate { get; set; }
        public System.DateTime RegistrationEndDate { get; set; }
        public System.DateTime TournamentStartDate { get; set; }
        public System.DateTime TournamentEndDate { get; set; }
        public System.DateTime CheckInBegins { get; set; }
        public System.DateTime CheckInEnds { get; set; }
        public int PlatformID { get; set; }
        public bool InProgress { get; set; }
        public string InviteCode { get; set; }
        public bool PublicRegistration { get; set; }
        public bool PublicViewing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<brackets> brackets { get; set; }
        public virtual gametypes gametypes { get; set; }
        public virtual platforms platforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentinvites> tournamentinvites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentteams> tournamentteams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tournamentusers> tournamentusers { get; set; }
    }
}
