//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TournamentModel()
        {
            this.Brackets = new HashSet<BracketModel>();
            this.TournamentUsers = new HashSet<TournamentUserModel>();
    		OnInit();
        }
    
        public int TournamentID { get; set; }
        public Nullable<int> GameTypeID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedByID { get; set; }
        public int WinnerID { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public int LastEditedByID { get; set; }
        public Nullable<decimal> EntryFee { get; set; }
        public decimal PrizePurse { get; set; }
        public bool IsPublic { get; set; }
        public System.DateTime RegistrationStartDate { get; set; }
        public System.DateTime RegistrationEndDate { get; set; }
        public System.DateTime TournamentStartDate { get; set; }
        public System.DateTime TournamentEndDate { get; set; }
        public System.DateTime CheckInBegins { get; set; }
        public System.DateTime CheckInEnds { get; set; }
        public int Platform { get; set; }
        public bool InProgress { get; set; }
        public string InviteCode { get; set; }
    	
    	partial void OnInit();
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BracketModel> Brackets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentUserModel> TournamentUsers { get; set; }
        public virtual GameTypeModel GameType { get; set; }
    }
}
