//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentBroadcasterModel
    {
        public int BroadcasterID { get; set; }
        public int TournamentID { get; set; }
        public int ServiceID { get; set; }
        public string BroadcasterName { get; set; }
    
        public virtual BroadcastServiceModel BroadcastService { get; set; }
        public virtual TournamentModel Tournament { get; set; }
    }
}
