CREATE TABLE [dbo].[Tournaments]
(
	[TournamentId]      INT            IDENTITY (1, 1) NOT NULL,
    [GameTypeId]        INT            NULL,
    [Title]             NVARCHAR (MAX) NOT NULL,
    [Description]       TEXT           NULL,
    [CreatedOn]         DATETIME       NOT NULL,
    [CreatedById]       INT            NOT NULL,
    [WinnerId]          INT            NOT NULL,
    [LastEditedOn]      DATETIME       NOT NULL,
    [LastEditedById]    INT            NOT NULL, 
	[EntryFee]              MONEY    NULL,
    [PrizePurse]            MONEY    NOT NULL,
    [IsPublic]              BIT      NOT NULL,
    [RegistrationStartDate] DATETIME NOT NULL,
    [RegistrationEndDate]   DATETIME NOT NULL,
    [TournamentStartDate]   DATETIME NOT NULL,
    [TournamentEndDate]     DATETIME NOT NULL,
    [CheckInBegins]         DATETIME NOT NULL,
    [CheckInEnds]           DATETIME NOT NULL,
    [Platform]              INT      NOT NULL, 
    CONSTRAINT [PK_Tournaments] PRIMARY KEY ([TournamentId]), 
)
